-- Reservation system schema and development data for PostgreSQL.
-- Docker runs this file automatically when a new PostgreSQL volume is created.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    created_at DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_key ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON users (email);

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    capacity INTEGER NOT NULL CHECK (capacity > 0),
    price_per_night NUMERIC(10, 2) NOT NULL CHECK (price_per_night >= 0),
    image_url VARCHAR(500),
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT reservations_date_range CHECK (end_date > start_date)
);

INSERT INTO rooms (id, room_number, name, description, capacity, price_per_night, image_url, active)
VALUES
    (1, '101', 'Classic Room', 'A bright room with a double bed, comfortable seating, and breakfast included.', 2, 89.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images.jpeg', true),
    (2, '201', 'Comfort Room', 'A spacious room with a dedicated lounge area, courtyard view, and modern amenities.', 3, 119.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(3).jpeg', true),
    (3, '301', 'Suite with Living Room', 'An elegant suite with a separate living room, panoramic windows, and thoughtful luxury details.', 4, 169.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(6).jpeg', true),
    (4, '102', 'Standard Single Room', 'A cozy and quiet room designed for solo travelers, featuring a single bed, ergonomic workspace, and high-speed Wi-Fi.', 1, 65.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(1).jpeg', true),
    (5, '103', 'Classic Twin Room', 'A welcoming room with two twin beds, large windows with garden views, and complimentary morning coffee.', 2, 95.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(2).jpeg', true),
    (6, '202', 'Deluxe King Room', 'A stylish deluxe room featuring a king-size bed, private furnished balcony, and marble bathroom.', 2, 139.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(4).jpeg', true),
    (7, '203', 'Family Comfort Room', 'An expansive family-friendly room with a queen bed and a pull-out sofa bed, plus a dining nook.', 4, 159.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(5).jpeg', true),
    (8, '302', 'Executive Suite', 'A refined top-floor suite with a king bed, meeting lounge, walk-in closet, and whirlpool bath.', 3, 199.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(7).jpeg', true),
    (9, '401', 'Presidential Penthouse', 'Exclusive rooftop penthouse featuring 360-degree panoramic views, private terrace, fireplace, and full concierge service.', 4, 299.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(8).jpeg', true),
    (10, '402', 'Skyline Studio', 'A modern studio with floor-to-ceiling windows, city views, and open-plan kitchen-living area.', 2, 179.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(9).jpeg', true),
    (11, '501', 'Honeymoon Loft', 'A romantic loft featuring sloped ceilings, ambient lighting, freestanding bathtub, and champagne on arrival.', 2, 220.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(10).jpeg', true),
    (12, '502', 'Grand Royal Suite', 'The pinnacle of luxury accommodation with master bedroom, guest room, private sauna, and butler service.', 6, 390.00, 'https://pub-b80ae22be51d442f91a5edc3c685d0af.r2.dev/images(11).jpeg', true)
ON CONFLICT (room_number) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    capacity = EXCLUDED.capacity,
    price_per_night = EXCLUDED.price_per_night,
    image_url = EXCLUDED.image_url,
    active = EXCLUDED.active;

SELECT setval(
    pg_get_serial_sequence('rooms', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM rooms), 1),
    true
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reservations_user_id_fkey'
    ) THEN
        ALTER TABLE reservations
            ADD CONSTRAINT reservations_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'reservations_room_id_fkey'
    ) THEN
        ALTER TABLE reservations
            ADD CONSTRAINT reservations_room_id_fkey
            FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS reservations_user_id_idx ON reservations (user_id);
CREATE INDEX IF NOT EXISTS reservations_room_dates_idx
    ON reservations (room_id, start_date, end_date);

-- Password for both demo accounts: password
-- Change or remove these accounts outside local development.
INSERT INTO users (username, email, password, role)
VALUES
    ('demo-user', 'demo.user@example.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'USER'),
    ('demo-admin', 'demo.admin@example.com', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'ADMIN')
ON CONFLICT (email) DO NOTHING;

INSERT INTO reservations (user_id, room_id, start_date, end_date, status)
SELECT demo_user.id, sample.room_id, sample.start_date, sample.end_date, sample.status
FROM users AS demo_user
CROSS JOIN (
    VALUES
        (1::BIGINT, CURRENT_DATE + 7, CURRENT_DATE + 10, 'APPROVED'::VARCHAR),
        (2::BIGINT, CURRENT_DATE + 14, CURRENT_DATE + 17, 'PENDING'::VARCHAR),
        (3::BIGINT, CURRENT_DATE + 28, CURRENT_DATE + 32, 'APPROVED'::VARCHAR)
) AS sample(room_id, start_date, end_date, status)
WHERE demo_user.email = 'demo.user@example.com'
  AND NOT EXISTS (
      SELECT 1
      FROM reservations AS existing
      WHERE existing.user_id = demo_user.id
        AND existing.room_id = sample.room_id
        AND existing.start_date = sample.start_date
        AND existing.end_date = sample.end_date
  );

COMMIT;
