services:
  postgres:
    image: postgres
    #platform: linux/x86_64
    container_name: postgres
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: reservations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./db_backup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  tomcat:
    build: src/test/java
    container_name: tomcat
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: reservations
      DB_USER: postgres
      DB_PASS: root
      #RABBIT_HOST: rabbitmq
      #MEMCACHED_HOST: memcached

